"""add title in weblink

Revision ID: 8f7eaab8ffeb
Revises: 97d66d104a4e
Create Date: 2025-10-20 19:59:23.464919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7eaab8ffeb'
down_revision: Union[str, Sequence[str], None] = '97d66d104a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weblink', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weblink', 'title')
    # ### end Alembic commands ###
